name: complex_task_flow
description: A powerful interaction flow controller for Flutter. Supports strictly ordered dialog sequences, smart replacement, branching, and buffering.
version: 0.0.1
homepage: https://github.com/yangxiaolongYasin/complex_task_flow.git  # 替换为你的 Github 地址
repository: https://github.com/yangxiaolongYasin/complex_task_flow.git # 替换为你的 Github 地址

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0